### ISSUE TITLE
Incorrect dependency line info

### ISSUE THREAD

**Issue by sambler** [FreshPorts/freshports#216]
After the description and pkg-plist, the dependency line is shown that another port would use if it depended on the current port. This line is not always correct and the heading for it is not always present.

Some ports show an incomplete python package line but install no py modules. By incomplete, the pkgname is missing eg. `${PYTHON_PKGNAMEPREFIX}>0:devel/doxygen@${PY_FLAVOR}`

Some ports show multiple lines - could these show (always show?) which dependency it would be used in? BUILD/LIB/RUN

Examples:
[textproc/py-docutils](https://www.freshports.org/textproc/py-docutils/) - correct
[devel/bison](https://www.freshports.org/devel/bison) - correct

[print/ghostscript9-agpl-base](https://www.freshports.org/print/ghostscript9-agpl-base) - no heading, otherwise correct. Has two lines, one belongs to LIB_DEPENDS, the other to BUILD or RUN.

[devel/doxygen](https://www.freshports.org/devel/doxygen) - no heading, shows as incomplete python pkg - not a py module

[devel/cmake](https://www.freshports.org/devel/cmake) - shows as incomplete python pkg - not a py module

[devel/libsigrok](https://www.freshports.org/devel/libsigrok) - no heading, two lines - lib line looks right, build/run line would not work as it does not install a cli tool.

These two would highlight port issues more than freshport issues. Shows that some of the port info is old.

[comms/gnuradio](https://www.freshports.org/comms/gnuradio) - no heading, multiple lines - python module line has no name and the module is installed without flavor support, so probably shouldn't be shown, the lib line is no longer valid, libvolk was split into separate port Apr 2020.

[devel/volk](https://www.freshports.org/devel/volk) - no heading, incomplete py module. While a py module is installed, this is mainly a lib port, the py module would need to be in a separate port to support flavors.

**Comment by dlangille** [comment]
See also #207 #180

**Comment by dlangille** [comment]
Let's start with [print/ghostscript9-agpl-base](https://www.freshports.org/print/ghostscript9-agpl-base) by clearing its cache:

```
[dan@supernews:/var/db/freshports/cache/ports] $ sudo rm -rf print/ghostscript9-agpl-base
[dan@supernews:/var/db/freshports/cache/ports] $ 
```

Fixed? Yes.  Let's do it for all of them.

```
[dan@supernews:/var/db/freshports/cache/ports] $ zfs list
NAME                  USED  AVAIL  REFER  MOUNTPOINT
freshports           5.86G  1.83G    23K  none
freshports/packages  3.45M  1.83G  3.44M  /var/db/freshports/cache/packages
freshports/ports     5.84G  1.83G  5.84G  /var/db/freshports/cache/ports
freshports/reserved    23K  1.83G    23K  none
[dan@supernews:/var/db/freshports/cache/ports] $ sudo zfs rollback freshports/ports@empty
[dan@supernews:/var/db/freshports/cache/ports] $ 
```

That's fixed all the missing heading.  Now. On the next stuff.

**Comment by dlangille** [comment]
How does FreshPorts know whether or not to put `${PYTHON_PKGNAMEPREFIX}` at the start of the line? `USES= python`

See [the code](https://github.com/FreshPorts/freshports/blob/master/classes/port-display.php#L462)

Then it "splits off the prefix, everything before the first -, inclusive", but that fails if the package does not have a [PKGNAMEPREFIX set to ${PYTHON_PKGNAMEPREFIX}](https://svnweb.freebsd.org/ports/head/textproc/py-docutils/Makefile?view=markup#l8), for example.

The database does not capture `PKGNAMEPREFIX` so let's try another approach.

If [line 467](https://github.com/FreshPorts/freshports/blob/master/classes/port-display.php#L467) is an empty string, we should not use `${PYTHON_PKGNAMEPREFIX}'` on line 468.

Let's try that on dev.

**Comment by dlangille** [comment]
Have a look at https://dev.freshports.org/devel/doxygen

Diff is:

```
[dan@dev-nginx01:~/www/classes] $ git diff
diff --git a/classes/port-display.php b/classes/port-display.php
index 88895275..1d885e73 100644
--- a/classes/port-display.php
+++ b/classes/port-display.php
@@ -392,7 +392,11 @@ class port_display {
                if ($USES_PYTHON) {
                        // split off the prefix, everthing before the first -, inclusive
                        $package_name_parts=explode('-', $port->package_name, 2);
-                       $HTML .=  '${PYTHON_PKGNAMEPREFIX}' . $package_name_parts[1];
+                       if ($package_name_parts[1] != '') {
+                               $HTML .=  '${PYTHON_PKGNAMEPREFIX}' . $package_name_parts[1];
+                       } else {
+                                $HTML .= $port->package_name;
+                       }
                } else {
                        $HTML .= $port->package_name;
                }

```

**Comment by dlangille** [comment]
For easy:

- https://dev.freshports.org/textproc/py-docutils/
- https://dev.freshports.org/devel/bison
- https://dev.freshports.org/print/ghostscript9-agpl-base
- https://dev.freshports.org/devel/doxygen
- https://dev.freshports.org/devel/cmake
- https://dev.freshports.org/devel/libsigrok
- https://dev.freshports.org/comms/gnuradio
- https://dev.freshports.org/devel/volk

**Comment by sambler** [comment]
The logic for adding `${PYTHON_PKGNAMEPREFIX}` would also apply to the addition of the `@${PY_FLAVOR}` suffix. doxygen and cmake don't show the prefix but still show the trailing flavour.

Python modules should use both prefix/suffix for flavours.

Other flavours only add a suffix?

For gnuradio, is that a caching problem as well? libvolk does not exist in the current pkg-plist. Does the DB still have the old pkg-plist? Do lines removed from pkg-plist also get removed from the DB?

**Comment by dlangille** [comment]
> The logic for adding `${PYTHON_PKGNAMEPREFIX}` would also apply to the addition of the `@${PY_FLAVOR}` suffix. doxygen and cmake don't show the prefix but still show the trailing flavour.

https://dev.freshports.org/devel/doxygen/ indicates `Flavors: there is no flavor information for this port.`

Looking in the [Makefile](https://svnweb.freebsd.org/ports/head/devel/doxygen/Makefile?view=markup) seems to indicate there are no flavors for this port.

I see what you mean at https://www.freshports.org/devel/doxygen/ but production does not have this fix. It's only on dev in my working copy of the website.

**Comment by dlangille** [comment]
> For gnuradio, is that a caching problem as well? 

I just cleared the cache on dev, and I see `gnuradio>0:comms/gnuradio@${PY_FLAVOR}`

I think that is incorrect. There is no reason for that suffix.  I see the problem in my code.  Fixed.

**Comment by dlangille** [comment]
> For gnuradio, is that a caching problem as well? libvolk does not exist in the current pkg-plist. Does the DB still have the old pkg-plist? Do lines removed from pkg-plist also get removed from the DB?

I do not see `libvolk` listed in the [gnuradio](https://svnweb.freebsd.org/ports/head/comms/gnuradio/Makefile?view=markup)

**Comment by dlangille** [comment]
Thank you for following upon this. It is great to get help.

**Comment by sambler** [comment]
In the gnuradio port Makefile, volk as a cli program is listed in BUILD_DEPENDS.

Historically volk was part of gnuradio, see [port commit 530370](https://svnweb.freebsd.org/ports?view=revision&revision=530370) mentions splitting volk into separate port.

In https://dev.freshports.org/comms/gnuradio the dependency lines still shows `libvolk.so:comms/gnuradio` which is no longer a lib installed by gnuradio - this is what I refer to in the pkg-plist being out of date. I expect this line was built from finding libvolk in the old plist, if this list in the DB was not updated when files were moved into the new devel/volk port, then that could be where it is finding it to create that dep line.

That would indicate changes to the pkg-plist cause files to be added to the DB but not removed. I expect deleting the plist entries in the DB before importing the updated pkg-plist would be the solution.

**Comment by dlangille** [comment]
I think you are questioning the second line here, as found at https://dev.freshports.org/comms/gnuradio/

```
Dependency lines:
* gnuradio>0:comms/gnuradio
* libvolk.so:comms/gnuradio
```

The `.so` lines are created at [line 487](https://github.com/FreshPorts/freshports/blob/master/classes/port-display.php#L487).

But the magic is in `pkg_plist_library_matches` which is created over in `[classes/ports.php](https://github.com/FreshPorts/freshports/blob/master/classes/ports.php)` on line 276:

```
array_to_json(regexp_match(pkg_plist, 'lib/[[:alpha:]]*?\.so')) AS pkg_plist_library_matches
```

Which is yes, `pkg-plist`.

Checking the database, we see that the `libvolk.so` value is found:

```
[dan@pg02:~] $ echo "select pkg_plist from ports_active where name = 'gnuradio';" | psql freshports.dev | grep libvolk.so
 lib/libvolk.so                                                               +
 lib/libvolk.so.1.%%MAJOR_VERSION%%                                           +
 lib/libvolk.so                                                               +
 lib/libvolk.so.1.2.2                                                         +
 lib/libvolk.so                                                               +
 lib/libvolk.so.1.%%MAJOR_VERSION%%                                           +
[dan@pg02:~] $ 
```

When I go looking for where that information is loaded into the database, I find nothing.  No reference to `pkg_plist` at all.

More searching led me to a table I'd forgotten about: `generate_plist`

It looks like the ingress code (backend, perl) was modified to use this table, instead of the `pkg_plist` column of the `ports` table. However, the website code still uses the `pkg-plist` column.

Let's change that.

**Comment by dlangille** [comment]
https://dev.freshports.org/comms/gnuradio/ looks better now.

**Comment by dlangille** [comment]
OK, more work done. See https://gist.github.com/dlangille/591a2a62a8bbe6fa92c5a268b99be1c8 for the details.

Of note, https://dev.freshports.org/sysutils/freeipmi has four libraries. https://www.freshports.org/comms/hamlib has one.

**Comment by dlangille** [comment]
All this work 'sponsored' by CISCO.

**Comment by dlangille** [comment]
NOTE https://dev.freshports.org/www/libnghttp2 is wrong, check the `pkg-plist`

**Comment by dlangille** [comment]
@sambler how is this looking now?

**Comment by sambler** [comment]
Yes definitely an improvement. Not sure if it can get to perfect, without manual cleanup.

Just to be picky - gnuradio doesn't list the old libvolk which is correct, but it isn't picking up libs that are installed by it.

**Comment by dlangille** [comment]
> Yes definitely an improvement. Not sure if it can get to perfect, without manual cleanup.

Manual cleanup is not sustainable.  A primary goal of FreshPorts development has always been minimize ongoing work.

> Just to be picky - gnuradio doesn't list the old libvolk which is correct, but it isn't picking up libs that are installed by it.

^ this is what I need to hear please.

Expanding the pkg-plist and looking at line 854 I see:

`lib/libgnuradio-analog.so`

Let's look at that.

**Comment by dlangille** [comment]
The code in `classes/ports.php` around line 270 invokes `pkg_plist(ports.id)`.  That function has a regular expression match which is too restrictive.

```
freshports.dev=# select pkg_plist(21609);
 pkg_plist 
-----------
 []
(1 row)


```
Let's look at that code:

```
CREATE OR REPLACE FUNCTION public.pkg_plist(
	bigint)
    RETURNS json
    LANGUAGE 'sql'
    COST 100
    STABLE PARALLEL UNSAFE
AS $BODY$
WITH tmp AS (
       select regexp_match(installed_file, 'lib/[[:alnum:]]*?\.so') as lib 
         from generate_plist
        where generate_plist.port_id = $1
   )
   select array_to_json(array(select distinct lib[1] from tmp where lib is not null));
$BODY$;
```

Let's try that `regexp_match` here:

```
freshports.dev=# select installed_file, regexp_match(installed_file, 'lib/[[:alnum:]]*?\.so') from generate_plist where port_id = 21609 and installed_file ilike 'lib/%.so' limit 5;
       installed_file        | regexp_match 
-----------------------------+--------------
 lib/libgnuradio-analog.so   | 
 lib/libgnuradio-audio.so    | 
 lib/libgnuradio-blocks.so   | 
 lib/libgnuradio-channels.so | 
 lib/libgnuradio-digital.so  | 
(5 rows)

freshports.dev=# 

```

It accepts only alphanumeric.  Let's accept anything but a slash instead:

```
freshports.dev=# select installed_file, regexp_match(installed_file, 'lib/[^/]*?\.so') from generate_plist where port_id = 21609 and installed_file ilike 'lib/%.so' limit 5;
       installed_file        |         regexp_match          
-----------------------------+-------------------------------
 lib/libgnuradio-analog.so   | {lib/libgnuradio-analog.so}
 lib/libgnuradio-audio.so    | {lib/libgnuradio-audio.so}
 lib/libgnuradio-blocks.so   | {lib/libgnuradio-blocks.so}
 lib/libgnuradio-channels.so | {lib/libgnuradio-channels.so}
 lib/libgnuradio-digital.so  | {lib/libgnuradio-digital.so}
(5 rows)

freshports.dev=# 

```

That looks better.

I have updated the stored procedure in the database.

@sambler Does https://dev.freshports.org/comms/gnuradio look better now?  Do ny other pages need attention?

**Comment by sambler** [comment]
The one's I've looked through look good now.

While there is value in showing differing build/lib/run dependency lines, do we need to list every lib available? Or is that just adding extra noise without value?

Unless you wanted to add a link or collapsable list that shows all dependency options.

**Comment by dlangille** [comment]
I thought about this last night:

Dependency lines:

* RUN/BUILD/ etc:
  * gnuradio>0:comms/gnuradio
* LIB:
  * libgnuradio-analog.so:comms/gnuradio
  * Expand this list (17 items)

**Comment by dlangille** [comment]
Although this was closed, the fix is not yet in production.

**Comment by dlangille** [comment]
Now in production.

**Comment by dlangille** [comment]
See also https://www.freshports.org/editors/vim-console/

**Comment by dlangille** [comment]
I think a regex is called for.  `py-##` is what we look for.

**Comment by dlangille** [comment]
I think this will work:

`$Is_A_Python_Port = preg_match('/^py[0-9][0-9]/', $port->package_name);`

The above fix is in devgit.freshports.org - please have a look there.

**Comment by mekanix** [comment]
I still see `${PYTHON_PKGNAMEPREFIX}>0:sysutils/ansible@${PY_FLAVOR}`. Shouldn't that be `${PYTHON_PKGNAMEPREFIX}ansible>0:sysutils/ansible@${PY_FLAVOR}`? I checked out [production](https://www.freshports.org/sysutils/ansible/) and [dev](http://devgit.freshports.org/sysutils/ansible/).

As I'm not really sure what the line should say, please tell me if I interpreted something wrong.

**Comment by dlangille** [comment]
You are correct.

The website is wrong.  Thank you.

**Comment by dlangille** [comment]
This will probably go to production over the weekend.
